[tool.poetry]
name = "resizer"
version = "0.1.0"
description = ""
authors = ["minseokk <minseokk@postech.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
python-resize-image = "^1.1.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
